// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irvaecqmzkecyispsxul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlydmFlY3FtemtlY3lpc3BzeHVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMjg0ODgsImV4cCI6MjA2NjgwNDQ4OH0.35a7ahwyX2GeZVMVzc1eDX4uyW82dvQqm85SxV1B00s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});